Add deal card editing form
kamabzalov/admss-client pull request #313
Opened 2024-04-12 18:12 UTC by JSDID

2024-04-12 20:58 UTC, kamabzalov commented
@JSDID , начало норм. Продолжайте

2024-04-15 07:32 UTC, kamabzalov reviewed
@JSDID еще не все доделано. Пока нет смысла ревьюить

2024-04-15 10:12 UTC, JSDID commented
![photo_2024-04-15_13-01-23](https://github.com/kamabzalov/admss-client/assets/102165823/1f9f5808-2028-4f05-b48b-dd1389f616d1)

2024-04-15 14:56 UTC, JSDID commented
![IMG_20240415_175344_911.jpg](https://github.com/kamabzalov/admss-client/assets/102165823/7dfa9c0f-4855-4de6-af92-a90ac6b781a0)

2024-04-15 14:58 UTC, JSDID commented
Нам нужны все dropdown list options, все что я нашел на беке - это Deal Type + Sale Type (их добавил)

![IMG_20240415_175729_562.jpg](https://github.com/kamabzalov/admss-client/assets/102165823/d8ab7d55-46c7-4484-8a91-9efcb7123a99)

2024-04-17 18:17 UTC, JSDID commented
![photo_2024-04-17_21-16-26](https://github.com/kamabzalov/admss-client/assets/102165823/83366e70-8b92-44e6-88ac-e4e10c5f1566)
![photo_2024-04-17_21-16-49](https://github.com/kamabzalov/admss-client/assets/102165823/9b72c2d5-2028-429b-a5f8-da26885842f5)

2024-04-17 18:18 UTC, JSDID commented
![photo_2024-04-17_21-18-10](https://github.com/kamabzalov/admss-client/assets/102165823/12e50881-ac21-4919-b909-941dc2687be8)

2024-04-17 18:20 UTC, JSDID commented
![photo_2024-04-17_21-19-47](https://github.com/kamabzalov/admss-client/assets/102165823/390f9617-88a3-4a1c-a1be-86ae23385cac)

2024-04-17 18:21 UTC, JSDID commented
![photo_2024-04-17_21-20-48](https://github.com/kamabzalov/admss-client/assets/102165823/1a262782-14f6-4d5c-9b9e-5f295a9374e4)

2024-04-17 18:23 UTC, JSDID commented
![photo_2024-04-17_21-23-34](https://github.com/kamabzalov/admss-client/assets/102165823/2b8e0d63-395b-4ea5-9ede-ba04a6bdeac2)

2024-04-17 18:24 UTC, JSDID commented
![photo_2024-04-17_21-24-05](https://github.com/kamabzalov/admss-client/assets/102165823/be368dcb-953d-417c-9cac-6e08e1fa1811)

2024-04-17 18:24 UTC, JSDID commented
![photo_2024-04-17_21-24-31](https://github.com/kamabzalov/admss-client/assets/102165823/885dda67-2fe2-429d-92bf-ea2691e79d24)

2024-04-17 18:25 UTC, JSDID commented
![photo_2024-04-17_21-25-15](https://github.com/kamabzalov/admss-client/assets/102165823/45155551-c559-41bb-82f5-bdfbb86cb42a)

2024-04-17 18:26 UTC, JSDID commented
![photo_2024-04-17_21-25-35](https://github.com/kamabzalov/admss-client/assets/102165823/605d13bc-6f9f-4103-94af-53f3c250f5d5)

2024-04-18 16:51 UTC, kamabzalov commented
Не сохраняются Sale date и First operated

2024-04-18 16:52 UTC, kamabzalov commented
@JSDID Warn Overdue After X Days тоже не сохраняется

2024-04-18 16:52 UTC, kamabzalov commented
@JSDID Account number не сохраняется

2024-04-22 12:34 UTC, kamabzalov commented
@JSDID конфликты

2024-04-26 20:33 UTC, kamabzalov commented
@JSDID конфликты

2024-04-27 20:31 UTC, kamabzalov commented
@JSDID дизайн обновлен - https://www.figma.com/file/BDg0gIw134tMRsEwMUa3G4/auto-dealer?type=design&node-id=4382-20537&mode=design&t=APOpQEFKh2NyFOVz-4

Сверьтесь, проверьте

2024-04-29 07:25 UTC, kamabzalov commented
@JSDID от бэка пришел ответ по полям

[deal_data_frontend.txt](https://github.com/kamabzalov/admss-client/files/15146158/deal_data_frontend.txt)

2024-04-30 17:00 UTC, JSDID commented
![image_2024-04-30_19-54-31](https://github.com/kamabzalov/admss-client/assets/102165823/fb0adaca-3ad9-4912-90b3-4f7aca2654a2)

2024-04-30 17:00 UTC, JSDID commented
![image_2024-04-30_19-54-31](https://github.com/kamabzalov/admss-client/assets/102165823/4dbe33a0-96ad-49af-bc9f-3974ce22033c)

2024-04-30 17:05 UTC, JSDID commented
![image_2024-04-30_19-54-31](https://github.com/kamabzalov/admss-client/assets/102165823/387b60d0-3732-4cdc-9a19-3e827f3414cc)
![image_2024-04-30_19-56-35](https://github.com/kamabzalov/admss-client/assets/102165823/529fca90-cdeb-4277-856e-7147de57c907)
![image_2024-04-30_20-04-16](https://github.com/kamabzalov/admss-client/assets/102165823/4b4f5483-dccc-459f-b8df-6ca0837f7bb8)

2024-04-30 17:13 UTC, JSDID commented
![image_2024-04-30_20-07-40](https://github.com/kamabzalov/admss-client/assets/102165823/de83c0bd-6d99-48cf-b906-7029995b34dc)

2024-04-30 17:14 UTC, kamabzalov commented
@JSDID теперь еще вот что надо сделать: есть кнопка Export to Web. Бэк ждет от нас модель данных, которые мы будем ему слать. Думаю, тут можно сделать по аналогии с печатью pdf (посмотрите в таблице инвентории) - там мы отправляем колонки и данные. Здесь можно также сделать, но надо только учесть колонки с сервисами: то есть если мы чекбокс у сервиса проставили, то можно сформировать объект (или массив объектов лучше, потому что можно выбрать несколько сервисов) с именем выбранного сервиса и ценой.

Жду от вас пример json

2024-04-30 17:19 UTC, JSDID commented
![image_2024-04-30_20-18-27](https://github.com/kamabzalov/admss-client/assets/102165823/f6855f44-768b-4ea1-91cc-b9d5324a02ed)

2024-04-30 17:19 UTC, JSDID commented
![image_2024-04-30_20-18-27](https://github.com/kamabzalov/admss-client/assets/102165823/28df13a7-2e60-49e0-95f4-a8f8e8f47e4a)

2024-05-08 07:29 UTC, kamabzalov requested changes
@JSDID 

сваггер и бэк обновлены

Pickup Payments:
GET /api/v1/deals/{dealuid}/ppaymenttotal
GET /api/v1/deals/{dealuid}/ppayments
POST /api/v1/deals/{dealuid}/ppayment
POST /api/v1/deals/{dealuid}/deleteppayment

Прочее
POST /api/v1/deals/{dealuid}/washout
POST /api/v1/deals/{dealuid}/recalculate

2024-05-08 09:52 UTC, kamabzalov commented
@JSDID конфликт

2024-05-09 09:16 UTC, JSDID commented
Переписаны интерфейсы, переписан компонент поиска компании с заданными фильтрами (сразу с фильтром "Dealers", например), обновлены поля форм Odometer, Seller, Tag. По поводу поиска с фильтром - было сказано беком в файле ответов. Different seller (вкладка Seller) - должна быть с таким параметром сразу.

2024-05-09 12:32 UTC, kamabzalov commented
@JSDID сохранение карточки deal можно считать полностью рабочим или что-то еще надо спросить?

2024-05-09 17:32 UTC, kamabzalov commented
@JSDID конфликт

2024-05-10 07:23 UTC, kamabzalov commented
@JSDID 
Исправить выбор инвентори в карточке deal
Сейчас вместо справочника inventory открывается справочник contacts (поле Vehicle)

2024-05-10 18:54 UTC, JSDID commented
Trade 1, Trade 2
Общий чекбокс Add to inventory. В ответе от сервера есть только addToInventory (без разделения Trade1 / Trade2)


Tag
Есть только значения номеров для Plate transfered, Exchanged Plate, Replaced Plate. Но для радиокнопок найти не смог.
Уточнить логику работы радиокнопок в целом: если выбран Title Only, то New Plates нет. Но как с ответами и запросами на сервер? Отправлять TitleOnly: 1, NewPlates: 0?
Так же и с остальными радиокнопками в этой форме.


Finances
Все данные сохраняются и читаются, washout + recalculate API добавлены, но пока не понятно что они делают. Сервер возвращает Status: OK, но в данной форме никакие значения не изменяются, если их заново перечитать.


Pickup payments
/deals/c431758e-7392-454d-8c36-924d31720e0c/ppayments
Сервер возвращает пустой массив. Нужны любые данные для дальнейшей обработки на фронте.


Contract Printing
/deals/c431758e-7392-454d-8c36-924d31720e0c/info
Не нашел полей в данном ответе. Возможно есть другой endpoint?

2024-05-10 19:26 UTC, kamabzalov requested changes
Почему изменения в аккаунтах и контактах? Задача про карточку deals
Посмотреть другие мои комментарии

2024-05-12 16:25 UTC, JSDID commented
в контактах добавлен поиск по типу самого контакта, так как этого требовал бек

2024-05-12 16:28 UTC, JSDID commented
Стили были перенесены в общий компонент стилей дашборда, так как они встречаются в каждой основной таблице. Для того что бы не было дублей стилей удалил их с других файлов стилей. Можно откатить назад при надобности

2024-05-12 18:26 UTC, JSDID commented
https://icecreamapps.com/v/dmte49a

2024-05-12 19:22 UTC, kamabzalov requested changes
@JSDID мой последний коммернт до сих пор актуален

2024-05-13 08:05 UTC, JSDID commented on src/sign/index.css
> +}
Проверю

2024-05-13 12:34 UTC, kamabzalov approved these changes

2024-05-13 12:34 UTC, merged