Update Export to Web
kamabzalov/admss-client pull request #319
Opened 2024-04-21 12:26 UTC by JSDID

2024-04-22 10:51 UTC, kamabzalov reviewed
@JSDID что мне надо спросить у бэка, чтобы вам дальше задачу доделать?

2024-04-22 12:15 UTC, JSDID commented
где взять serviceName1 ... serviceNameN

2024-04-26 20:32 UTC, kamabzalov commented
@JSDID конфликт

2024-04-27 18:34 UTC, kamabzalov reviewed
@JSDID 

1. чекбоксы не прожимаются обратно.
2.  Нажатие на чекбоксы устанавливает их по всей таблице
3. Настройки не сохраняются
4. tooltip уехал вправо
5. описание не вижу (при нажатии на стрелку вниз)


Штраф за непроверку своей работы

2024-04-28 09:39 UTC, JSDID commented
Нет поля description . Самое подходящее по смыслу - DealerComments![IMG_20240428_123607_282.jpg](https://github.com/kamabzalov/admss-client/assets/102165823/6a01ca38-d896-48cd-8a9b-cdfe7cb1579f)

2024-04-28 12:16 UTC, kamabzalov commented
@JSDID билд упал

2024-04-28 12:16 UTC, kamabzalov commented
@JSDID нажав на "Details", можно посмотреть причины

2024-04-30 17:23 UTC, kamabzalov commented
@JSDID при нажатии на карандаш надо проваливаться в карточку инвентории.
И карандаша и вторая иконка рядом стали зелеными. Не уверен, что в дизайне также

2024-05-01 17:55 UTC, kamabzalov reviewed
@JSDID 
дубли запросов

![image](https://github.com/kamabzalov/admss-client/assets/49127222/1777d7a2-e999-4a2c-820a-5618538e8b9a)

2024-05-02 14:14 UTC, JSDID commented
пример JSONа можно посмотреть в консоли

2024-05-03 18:53 UTC, kamabzalov requested changes
@JSDID поговорил с бэком - json устраивает
Единственное - если я выбираю инвенторию (но не выбираю сервисы), то ее тоже добавляем в json, но свойство services делаем пустым массивом или лучше вообще не добавлять

![image](https://github.com/kamabzalov/admss-client/assets/49127222/ca456619-b841-45ee-a6ca-a8fc7cc45503)

2024-05-09 08:18 UTC, kamabzalov commented
@JSDID наведите порядок с коммитами (rebase)

И добавьте новый api
GET /api/v1/external/{useruid}/schedule - list scheduled tasks
GET /api/v1/external/{taskuid}/exportinfo - export task info

POST /api/v1/external/{useruid}/export - add export task - Export NOW
POST /api/v1/external/{useruid}/schedule - add export task to the schedule

2024-05-09 12:31 UTC, kamabzalov reviewed
Нажимаю на кнопку Export now или Schedule - api не вызывается

2024-05-09 17:50 UTC, JSDID commented
АПИ добавил, но возвращает ошибку

2024-05-09 18:07 UTC, kamabzalov commented on src/http/services/export-to-web.service.ts
> +        const request = await authorizedUserApiInstance.get<BaseResponse[]>(
Get методы можно выпилить. Они нам тут не нужны пока что

2024-05-09 18:07 UTC, kamabzalov commented on src/common/models/user/index.ts
> +    selectedFilterOptions?: FilterOptions[] | any;
А почему any нам нужен?

2024-05-09 18:07 UTC, kamabzalov commented on src/dashboard/inventory/index.tsx
> +                        <h2 className='card-header__title uppercase m-0'>Inventory</h2>
почему изменения в инвентории в задаче про export to web?

2024-05-09 18:12 UTC, JSDID commented on src/common/models/user/index.ts
> +    selectedFilterOptions?: FilterOptions[] | any;
для того что-бы была возможность работать с другими фильтрами (у нас фильтра постоянно новые создаются, и нельзя на перед написать типы)

2024-05-09 18:17 UTC, kamabzalov commented on src/dashboard/inventory/index.tsx
> +                        <h2 className='card-header__title uppercase m-0'>Inventory</h2>
В следующий раз просите меня создавать для рефакторинга отдельную задачу

2024-05-09 18:18 UTC, kamabzalov commented on src/common/models/user/index.ts
> +    selectedFilterOptions?: FilterOptions[] | any;
@JSDID но фильтры же всегда будут массивом. Разве нет?

2024-05-09 19:05 UTC, kamabzalov approved these changes

2024-05-09 19:05 UTC, merged