Added page user settings
kamabzalov/admss-client pull request #328
Opened 2024-04-24 17:19 UTC by JSDID

2024-04-24 18:43 UTC, kamabzalov reviewed
@JSDID читайте описание задачи - удаление и др кнопки ничего не делают. Задача не только про верстку

2024-04-24 19:18 UTC, JSDID commented
1. Для чего нужны checkboxes? Будут ли еще кнопки "пакетных" обработок?
2. Как должно происходить действие добавление group? При щелчке на "New Group" что должно происходить?

2024-04-25 07:52 UTC, kamabzalov commented
> 1. Для чего нужны checkboxes? Будут ли еще кнопки "пакетных" обработок?
> 2. Как должно происходить действие добавление group? При щелчке на "New Group" что должно происходить?

@JSDID добавление отображено на соседнем фрейме в figma: нажали на New Group -> появляется новая строка с input и кнопкой Save И так далее

2024-04-25 08:49 UTC, kamabzalov commented
@JSDID по поводу чекбоксов: пока просто сделайте их кликабельными. 
Итог: надо доделать возможность добавления новой группы и ее удаления/редактирования (первые 4, которые в дизайне, не удалять - они по умолчанию)

2024-04-25 13:26 UTC, kamabzalov requested changes
Не могу сохранить изменения группы - Save не работает

2024-04-25 17:45 UTC, kamabzalov commented
New group должно добавлять input и с кнопкой а не создавать группу на лету
Редактирование и поле для чекбоксов будут обновления от бэка

2024-04-26 07:32 UTC, kamabzalov commented
@JSDID конфликт

2024-04-26 11:25 UTC, kamabzalov commented
@JSDID конфликты

2024-04-26 16:54 UTC, kamabzalov reviewed
New group не работает
При нажатии на чекбокс кнопка становится белая
При редактировании никакой апи не вызывается

2024-04-26 19:53 UTC, kamabzalov reviewed
@JSDID чекбокс не прожимается

2024-04-26 20:14 UTC, kamabzalov reviewed
Прелоадер добавьте - нажимаю на чекбокс и не понятно что происходит сохранение

2024-04-26 20:24 UTC, kamabzalov approved these changes

2024-04-26 20:24 UTC, merged