Add combobox
kamabzalov/admss-client pull request #330
Opened 2024-04-25 14:34 UTC by JSDID

2024-04-25 15:28 UTC, kamabzalov reviewed
Сохранение location name не работает

2024-04-25 15:41 UTC, JSDID commented
Она не работала и раньше, потому что сказали что ендпоинт добавят позже

2024-04-25 17:42 UTC, kamabzalov commented
Location есть в поле инвентории locationuid - нужно связать по нему первый dropdown
Group class - заменить на апи из предыдущей задачи (то есть группы в настройках и тут - это одни и те же группы)
Проверить сохранение

2024-04-26 11:29 UTC, kamabzalov reviewed
@JSDID 
![image](https://github.com/kamabzalov/admss-client/assets/49127222/abee71d3-5fb8-4bbc-8685-a079b4394826)

2024-04-26 11:33 UTC, kamabzalov commented
@JSDID выбираю New group, но на бэк по прежнему отправляется Cars

2024-04-26 19:35 UTC, kamabzalov requested changes
@JSDID поле с бэка приходит, но в dropdown не заполняется

![image](https://github.com/kamabzalov/admss-client/assets/49127222/4b15d2f2-b0cc-41f5-bf27-9258591be812)

2024-04-26 20:24 UTC, kamabzalov commented
@JSDID конфликты

2024-04-26 20:29 UTC, kamabzalov reviewed
@JSDID для групп в карточке инвентории добавится метод **grouplistactive**
надо его использовать

2024-04-26 21:21 UTC, kamabzalov approved these changes

2024-04-26 21:22 UTC, merged