Fix fields
kamabzalov/admss-client pull request #354
Opened 2024-05-04 10:56 UTC by JSDID

2024-05-04 14:11 UTC, kamabzalov reviewed
Какая задача тут решена?

2024-05-04 14:14 UTC, JSDID commented
Эта 

![photo_2024-05-04_17-13-09](https://github.com/kamabzalov/admss-client/assets/102165823/043f3b7b-a909-4f28-894b-ffea4ffa31cb)

2024-05-04 14:16 UTC, JSDID commented
Вернуть и записать в другую Ветку?

2024-05-04 14:19 UTC, kamabzalov commented
> Эта
> 
> ![photo_2024-05-04_17-13-09](https://private-user-images.githubusercontent.com/102165823/327954133-043f3b7b-a909-4f28-894b-ffea4ffa31cb.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ4MzI2MzEsIm5iZiI6MTcxNDgzMjMzMSwicGF0aCI6Ii8xMDIxNjU4MjMvMzI3OTU0MTMzLTA0M2YzYjdiLWE5MDktNGYyOC04OTRiLWZmZWE0ZmZhMzFjYi5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwNFQxNDE4NTFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMjkzOWU1MTA4OWEwYzcyN2M3OThmMTUxOGVkMGM0NzM0YTRlNzc3ZWM2NGY4MzBjYWQyOTc0N2RhN2RkYWNjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.tf9lPWJPYXzldZ2cngaIK_SEISpZmVB2b_eUnYkEywQ)

А почему изменения в стилях и в разделе Expenses?

2024-05-04 19:03 UTC, kamabzalov requested changes

2024-05-04 19:03 UTC, kamabzalov commented on src/dashboard/inventory/form/purchase/expenses/index.tsx
> +
Как изменения в этом файле связаны с задачей??

Штраф

2024-05-06 09:26 UTC, kamabzalov approved these changes

2024-05-06 09:26 UTC, merged