Add a location filter
kamabzalov/admss-client pull request #356
Opened 2024-05-04 16:01 UTC by JSDID

2024-05-04 16:01 UTC, JSDID commented
В сваггере по поводу фильтров ничего

2024-05-04 16:02 UTC, JSDID commented
Какое значение отправлять? Как обозвать поле?
location=locName?

2024-05-04 16:07 UTC, JSDID commented
В каком виде и куда отправлять запрос для переключения фильтра локации?

2024-05-04 19:01 UTC, kamabzalov reviewed
@JSDID дизайн не соблюден

![image](https://github.com/kamabzalov/admss-client/assets/49127222/24d6df46-9e4e-4095-8931-238190492cf5)

![image](https://github.com/kamabzalov/admss-client/assets/49127222/03221197-8ddd-4351-84f9-736c41d320f4)

2024-05-06 13:24 UTC, kamabzalov reviewed
@JSDID читайте задачу внимательно

2024-05-07 12:00 UTC, kamabzalov commented on src/dashboard/index.css
> +
Это что за стили? Почему они в этой задаче нужны?

2024-05-07 12:00 UTC, kamabzalov commented on src/dashboard/inventory/index.css
> +}
У кнопки в дизайне есть border (в фигме). Соблюдайте дизайн!

2024-05-07 13:26 UTC, JSDID commented on src/dashboard/index.css
> +
Цвет фона при наведении

2024-05-07 13:27 UTC, JSDID commented on src/dashboard/inventory/index.css
> +}
![IMG_20240507_162645_983.jpg](https://github.com/kamabzalov/admss-client/assets/102165823/c05385cb-892a-43fa-a798-9899f3ead28b)

если убрать будут такие

2024-05-07 13:45 UTC, kamabzalov commented on src/dashboard/inventory/index.css
> +}
Что убрать? Я написал коммент про соблюдение дизайна

2024-05-07 15:16 UTC, JSDID commented on src/dashboard/index.css
> +
![IMG_20240507_181640_771.jpg](https://github.com/kamabzalov/admss-client/assets/102165823/9a2f1847-140b-4232-972f-5f37c0fdf864)

2024-05-07 16:37 UTC, kamabzalov reviewed
@JSDID Стрелка у кнопки переключается быстро, еще даже меню неоткрылось

2024-05-07 17:39 UTC, JSDID commented
Есть https://icecreamapps.com/v/fuyb4gn

2024-05-07 17:39 UTC, kamabzalov commented
@JSDID для фильтрации инвентории по location используем в запросе locationuid

2024-05-08 07:27 UTC, kamabzalov commented
@JSDID конфликт

2024-05-08 07:58 UTC, kamabzalov requested changes
@JSDID конфликты!

2024-05-08 08:49 UTC, JSDID commented
Что-бы читались настройки нужно будет вернуть закоментированный код

Ч![IMG_20240508_114841_840.jpg](https://github.com/kamabzalov/admss-client/assets/102165823/0d7c08b8-8d43-4cb0-8471-3c0c883e2708)

2024-05-08 08:50 UTC, JSDID commented
Что-бы читались настройки нужно будет вернуть закоментированный код

Ч![IMG_20240508_114841_840.jpg](https://github.com/kamabzalov/admss-client/assets/102165823/0d7c08b8-8d43-4cb0-8471-3c0c883e2708)

2024-05-08 08:53 UTC, kamabzalov commented
> Что-бы читались настройки нужно будет вернуть закоментированный код
> 
> ![IMG_20240508_114841_840.jpg](https://private-user-images.githubusercontent.com/102165823/328821701-0f9a8262-4600-4153-8966-34c1ec07d6ee.jpg?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUxNTg2MjMsIm5iZiI6MTcxNTE1ODMyMywicGF0aCI6Ii8xMDIxNjU4MjMvMzI4ODIxNzAxLTBmOWE4MjYyLTQ2MDAtNDE1My04OTY2LTM0YzFlYzA3ZDZlZS5qcGc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTA4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUwOFQwODUyMDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01NDdlMGJiMjk1NzUzYzI2MGY4MmQ5ZGRmMzliYTE1ZTliZTA3ZTVmNmQxMTRiOWY1ZDA0NTEwNmVmZWE2OTBmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.ZstkmUMqD8Z8uRzotyXSWi8XoPtL3wm86LqKWGZH0EU)

Не очень понял. Надо же просто отфильтровать инвентории  по локации (как вы сделали в другой задаче по типу). О каких настройках вы говорите? Зачем закомментирован код?

2024-05-08 09:15 UTC, JSDID commented
Имею в виду сохранение пользовательских настроек

Раскосматить Вам?

2024-05-08 09:19 UTC, kamabzalov commented
> Имею в виду сохранение пользовательских настроек
> 
> Раскосматить Вам?

Конечно. Вообще не понимаю, зачем вы закомментили? Это другая функциональность и она должна работать

2024-05-08 09:51 UTC, kamabzalov approved these changes

2024-05-08 09:51 UTC, merged