Add commit
kamabzalov/admss-client pull request #363
Opened 2024-05-06 11:55 UTC by JSDID

2024-05-06 12:06 UTC, kamabzalov reviewed
@JSDID сверьтесь с дизайном - https://www.figma.com/file/BDg0gIw134tMRsEwMUa3G4/auto-dealer?type=design&node-id=3248-25570&mode=design&t=b9b6UmFZVJ8wCxVS-0

2024-05-06 13:21 UTC, kamabzalov reviewed
1. Почему у стрелки tooltip  c текстом "Edit"? Это логично?
2. Иконка слева не работает

2024-05-08 09:51 UTC, kamabzalov commented
@JSDID конфликт

2024-05-09 12:27 UTC, kamabzalov commented on src/dashboard/inventory/form/purchase/expenses/index.tsx
> +                                            tooltip='Edit'
Идентичный tooltip на разные операции

2024-05-10 12:09 UTC, kamabzalov reviewed
Похоже ваши стили поломали фильтр по локации 

![image](https://github.com/kamabzalov/admss-client/assets/49127222/894d39c7-e61a-4cc8-af5b-5357df72aa0e)

2024-05-10 12:09 UTC, kamabzalov commented on src/dashboard/inventory/form/purchase/expenses/index.tsx
> +    // const [buttonDisabled, setButtonDisabled] = useState<boolean>(true);
Убираем

2024-05-10 12:09 UTC, kamabzalov commented on src/dashboard/inventory/form/purchase/expenses/index.tsx
> +        setExpenseNotes("");
Можно ли вместо нескольких state объединить в один?

2024-05-10 12:09 UTC, kamabzalov commented on src/dashboard/inventory/form/purchase/expenses/index.tsx
> +            // expenseData.itemuid = currentExpenseUid;
Убрать

2024-05-10 12:09 UTC, kamabzalov commented on src/dashboard/inventory/form/purchase/expenses/index.tsx
> +            setCurrentExpenseUid(itemuid);
Аналогичный вопрос про один state (как объект)

2024-05-10 13:30 UTC, kamabzalov reviewed
@JSDID не все комменты исправлены!

2024-05-10 19:17 UTC, kamabzalov reviewed
А почему notes в две строки?

![image](https://github.com/kamabzalov/admss-client/assets/49127222/29c9103e-5545-42f5-b492-acc15b2ab1d7)

2024-05-10 19:19 UTC, kamabzalov reviewed
Редактирую строку табилцы (форма вверху),  сохраняю, но данные из таблицы не обновились

2024-05-10 19:20 UTC, kamabzalov reviewed
Vendor не проставляется при клике на редаткирование

2024-05-10 19:23 UTC, JSDID commented
Vendor проставляется. Просто поле пустое. Если выбрать первую запись (Kamil) - то будет все ок

про редактирование писал - оно не работает. Нужны детали от бека

2024-05-10 19:27 UTC, kamabzalov commented
> Vendor проставляется. Просто поле пустое. Если выбрать первую запись (Kamil) - то будет все ок
> 
> про редактирование писал - оно не работает. Нужны детали от бека

@JSDID дайте ссылку на инвенторию - где я могу посмотреть

2024-05-12 19:15 UTC, kamabzalov requested changes
@JSDID перестало работать создание Expense.

Проверить весь цикл работы с expense

2024-05-12 19:31 UTC, kamabzalov commented
@JSDID чтобы заработало изменение текущей expense, бэк просит передавать в теле запроса **itemuid** (id редактируемой expense, как и в урле)

2024-05-13 17:44 UTC, kamabzalov commented
@JSDID последний коммит 10 часов назад - ничего не изменилось

2024-05-13 18:06 UTC, kamabzalov commented on src/http/services/expenses.service.ts
> +        if (expenseuid && expenseuid !== "0") {
А можно 0 как число передавать? Некрасивая проверка прям

2024-05-14 07:20 UTC, kamabzalov approved these changes

2024-05-14 07:20 UTC, merged