Added reports
kamabzalov/admss-client pull request #375
Opened 2024-05-20 15:21 UTC by JSDID

2024-05-20 19:07 UTC, kamabzalov requested changes
Логику для "New collection" реализуйте

2024-05-20 19:07 UTC, kamabzalov commented on src/dashboard/reports/index.tsx
> +        id: "1",
А зачем нам тут моки? Или это временно? И почему id - строки?

2024-05-20 19:07 UTC, kamabzalov commented on src/dashboard/reports/index.tsx
> +            setUser(user);
Почему мы здесь устанавливаем юзера?

2024-05-20 19:07 UTC, kamabzalov commented on src/http/services/reports.service.ts
> +        // TODO: add error handler
Сразу добавляйте обработку ошибок (тоастер с ошибкой)

2024-05-20 19:07 UTC, kamabzalov commented on src/http/services/reports.service.ts
> +        // TODO: add error handler
Сразу добавляйте обработку ошибок (тоастер с ошибкой)

2024-05-20 19:07 UTC, kamabzalov commented on src/http/services/reports.service.ts
> +        // TODO: add error handler
Аналогично для всего раздела

2024-05-21 06:54 UTC, JSDID commented
Хочу уточнить еще по поводу reports, а именно New collection. Как она точно должна работать? Выбирает из текущих категорий (вкладок) любые формы, и создает отдельный массив с этими репортами?

2024-05-21 06:54 UTC, JSDID commented
![IMG_20240521_095444_930.jpg](https://github.com/kamabzalov/admss-client/assets/102165823/0df50c48-66f5-4d8f-8aef-ea2a01b5999e)

2024-05-21 12:37 UTC, kamabzalov reviewed
@JSDID ожидаю ответы на мои коментарии

2024-05-21 13:19 UTC, JSDID commented
Моки нужны, чтобы показать работу и готовый дизайн

2024-05-21 13:19 UTC, JSDID commented
Мы же не будем пустую табы показывать. Когда будет апи - удалим

2024-05-21 15:47 UTC, kamabzalov approved these changes

2024-05-21 15:47 UTC, merged